### ISSUE TITLE
It's not working properly

### ISSUE THREAD

**Issue by alikoganyan** [mailium/oauth-client-php#1]
It redirects to `appid.mailium.net` asks me to login, after, it redirects me to sendloop and asks to login there.
After all this I was hoping to be redirected back to my app, but, guess what, it shows me welcome page of sendloop `http://appid.sendloop.com/welcome`

**Comment by merthurturk** [comment]
We can't reproduce the issue on our end. With the following test script (a very basic one), oauth flow works perfect. As we don't know your implementation details, we can't help you further. After comparing your own implementation with the following, if you are still having the same issue please send an email to hello@sendloop.com with the details of your implementation.

```
<?php

require 'vendor/autoload.php';

use MailiumOauthClient\MailiumOauthClient;

$oauthClient = new MailiumOauthClient();
$oauthClient->setClientID("CLIENT_ID");
$oauthClient->setClientSecret("CLIENT_SECRET");
$oauthClient->setRedirectUri("APP_URL");

$oauthClient->addScope(MailiumOauthClient::SCOPE_CAMPAIGN_READ);
$oauthClient->setTokenStoreCallbackFunction("storeToken");

function storeToken($owner, $token) {
    // Store the token and owner relation on persistent storage...
}

if (isset($_GET['code'])) {
    $oauthClient->authorize($_GET['code']);

    print_r($oauthClient->getResourceOwner());
    exit;

} else {
    $authorizationUrl = $oauthClient->createAuthorizationUrl();
    header('Location: ' . $authorizationUrl);
    exit;
}
```
